Repository qri-io/website, pull requests merged in 2020-02, with the labels that each got.

#164 feat: add unfurling meta
  content/docs/dataset-components/body.md
  content/docs/dataset-components/commit.md
  content/docs/dataset-components/meta.md
  content/docs/dataset-components/overview.md
  content/docs/dataset-components/readme.md
  content/docs/dataset-components/structure.md
  content/docs/dataset-components/transform.md
  content/docs/getting-started/qri-cli-quickstart.md
  content/docs/getting-started/qri-desktop-quickstart.md
  content/docs/getting-started/what-is-qri.md
  content/docs/integrating-qri/working-directories.md
  content/docs/reference/cli_commands.md
  content/docs/reference/content-addressing.md
  content/docs/reference/dataset.md
  content/docs/reference/glossary.md
  content/docs/reference/ipfs_to_qri.md
  content/docs/reference/logbook.md
  content/docs/reference/qri-system-files.md
  content/docs/starlark/examples.md
  content/docs/starlark/starlib.md
  content/docs/starlark/syntax.md
  content/docs/working-with-datasets/naming.md
  content/docs/working-with-datasets/publishing.md
  content/docs/working-with-datasets/versioning.md
  gatsby-node.js
  src/components/Head.js
  src/html.js
  src/layouts/data-story.js
  src/layouts/docs.js
  src/layouts/index.js
  src/layouts/markdown-page.js
  src/pages/404.js
  src/pages/beta.js
  src/pages/data-stories/brooklyn-bus-times.md
  src/pages/data-stories/map-test.md
  src/pages/docs.js
  src/pages/download.js
  src/pages/index.js
  src/pages/jobs/apply.js
  src/pages/jobs/index.js
  src/pages/jobs/job-backend-software-engineer.md
  src/pages/jobs/job-data-research-assistant.md
  src/pages/jobs/job-frontend-software-engineer.md
  src/pages/papers/deterministic-querying.js
  static/img/twitter_card_image.png
Labels: feat

#167 feat(scripts): add scripts for updating starlark
  content/docs/reference/starlib.md
  readme.md
  scripts/outline_html_viz_docs_template.md
  scripts/outline_starlib_docs_template.md
  scripts/update_html_viz.sh
  scripts/update_starlib.sh
  yarn.lock
Labels: feat

#172 refactor: desktop-quickstart - some rewrites and added images
  content/docs/getting-started/qri-cli-quickstart.md
  content/docs/getting-started/qri-desktop-quickstart.md
  src/components/ImageWithCaption.js
  src/pages/data-stories/brooklyn-bus-times.md
  src/scss/_main.scss
  static/img/screenshots/checkout-modal.png
  static/img/screenshots/collection-with-datasets.png
  static/img/screenshots/csv-workbench-history.png
  static/img/screenshots/csv-workbench-meta-edit-commit.png
  static/img/screenshots/csv-workbench-meta-edit.png
  static/img/screenshots/csv-workbench-rename.png
  static/img/screenshots/csv-workbench-status.png
  static/img/screenshots/csv-workbench-view-commit.png
  static/img/screenshots/loading.png
  static/img/screenshots/local-search.png
  static/img/screenshots/network-preview-with-local.png
  static/img/screenshots/network-preview.png
  static/img/screenshots/network-with-published-dataset.png
  static/img/screenshots/no-datasets-collection.png
  static/img/screenshots/publish.png
  static/img/screenshots/search.png
  static/img/screenshots/signup.png
  static/img/screenshots/tos.png
  static/img/screenshots/unpublish-hamburger.png
  static/img/screenshots/workbench-checkout.png
Labels: enhancement

#173 starlark docs cleanup work
  content/docs/dataset-components/transform.md
  content/docs/reference/starlib.md
  content/docs/starlark/examples.md
  content/docs/starlark/introduction.md
  content/docs/starlark/runtime.md
  gatsby-node.js
  scripts/outline_starlib_docs_template.md
  scripts/update_starlib.sh
Labels: docs, starlark

#176 docs(starlib): add section on importing starlib modules
  content/docs/reference/starlib.md
  content/docs/starlark/starlib.md
  scripts/outline_starlib_docs_template.md
  scripts/update_starlib.sh
Labels: docs, starlark

#178 Remove link to cli-manual
  content/docs/getting-started/qri-cli-quickstart.md
Labels: fix

#179 feat(install.sh): add /install.sh redirect
  gatsby-node.js
Labels: feat
